table DIM_GruppiVendita

	column Gruppo
		dataType: string
		summarizeBy: none
		sourceColumn: Gruppo

		annotation SummarizationSetBy = Automatic

	column CodiceCategoria
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceCategoria

		annotation SummarizationSetBy = Automatic

	partition DIM_GruppiVendita = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    GRUPPI_VENDITE_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="GRUPPI_VENDITE",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(GRUPPI_VENDITE_,{{"Codice Categoria", "CodiceCategoria"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
