table DIM_Fornitori

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Città
		dataType: string
		summarizeBy: none
		sourceColumn: Città

		annotation SummarizationSetBy = Automatic

	column Provincia
		dataType: string
		summarizeBy: none
		sourceColumn: Provincia

		annotation SummarizationSetBy = Automatic

	column CodiceFornitore
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceFornitore

		annotation SummarizationSetBy = Automatic

	partition DIM_Fornitori = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    FORNITORI_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="FORNITORI",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(FORNITORI_,{{"Codice Fornitore", "CodiceFornitore"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
