table DIM_Progetto

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column CodiceProgetto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceProgetto

		annotation SummarizationSetBy = Automatic

	partition DIM_Progetto = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    PROGETTO_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="PROGETTO",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(PROGETTO_,{{"Codice Progetto", "CodiceProgetto"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
