table DIM_Deposito

	column NomeDeposito
		dataType: string
		summarizeBy: none
		sourceColumn: NomeDeposito

		annotation SummarizationSetBy = Automatic

	column CodiceDeposito
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceDeposito

		annotation SummarizationSetBy = Automatic

	partition DIM_Deposito = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    UBICAZIONE_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="UBICAZIONE",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(UBICAZIONE_,{{"Nome", "NomeDeposito"}, {"Codice Ubicazione", "CodiceDeposito"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
