table DIM_PianoConti

	column CodiceConto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceConto

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Reparto
		dataType: string
		summarizeBy: none
		sourceColumn: Reparto

		annotation SummarizationSetBy = Automatic

	column Progetto
		dataType: string
		summarizeBy: none
		sourceColumn: Progetto

		annotation SummarizationSetBy = Automatic

	partition DIM_PianoConti = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    PIANO_DEI_CONTI_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="PIANO_DEI_CONTI",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(PIANO_DEI_CONTI_,{{"Codice Conto", "CodiceConto"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
