table DIM_Reparto

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column CodiceReparto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceReparto

		annotation SummarizationSetBy = Automatic

	partition DIM_Reparto = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    REPARTO_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="REPARTO",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(REPARTO_,{{"Codice Reparto", "CodiceReparto"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione
