table DIM_Articoli

	column Nome
		dataType: string
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column CostoUnitario
		dataType: double
		summarizeBy: sum
		sourceColumn: CostoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UltimoCostoDiretto
		dataType: double
		summarizeBy: sum
		sourceColumn: UltimoCostoDiretto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GruppoRegistrazioneProdotto
		dataType: string
		summarizeBy: none
		sourceColumn: GruppoRegistrazioneProdotto

		annotation SummarizationSetBy = Automatic

	column NumeroAccisa
		dataType: string
		summarizeBy: none
		sourceColumn: NumeroAccisa

		annotation SummarizationSetBy = Automatic

	column DensitàTA
		dataType: double
		summarizeBy: sum
		sourceColumn: DensitàTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Densità15C
		dataType: double
		summarizeBy: sum
		sourceColumn: Densità15C

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GruppoProdotto = ```
			
			    SWITCH( TRUE(),
			        DIM_Articoli[CodiceArticolo] IN {"1","1T"},"MIX",
			        DIM_Articoli[CodiceArticolo] IN {"2","2T"},"PROPANO",
			        DIM_Articoli[CodiceArticolo] IN {"2M","2MT"},"BLEND",
			        DIM_Articoli[CodiceArticolo] IN {"3","3T"},"BUTANO",
			        DIM_Articoli[CodiceArticolo] IN {"D"},"DENAT",
			        BLANK()
			    )
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceArticolo

		annotation SummarizationSetBy = Automatic

	column GruppoCategoria
		dataType: string
		summarizeBy: none
		sourceColumn: GruppoCategoria

		annotation SummarizationSetBy = Automatic

	partition DIM_Articoli = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    ARTICOLI_ = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="ARTICOLI",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(ARTICOLI_,{{"Codice Articolo", "CodiceArticolo"}, {"Unit Cost", "CostoUnitario"}, {"Last Direct Cost", "UltimoCostoDiretto"}, {"Gen_ Prod_ Posting Group", "GruppoRegistrazioneProdotto"}, {"Nr_ Accisa", "NumeroAccisa"}, {"Densità T_A_", "DensitàTA"}, {"Densità 15 C", "Densità15C"}, {"GruppoArticolo", "GruppoCategoria"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
