table FACT_Magazzino

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceArticolo

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CodiceDeposito
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceDeposito

		annotation SummarizationSetBy = Automatic

	column TipoMovimento
		dataType: string
		summarizeBy: none
		sourceColumn: TipoMovimento

		annotation SummarizationSetBy = Automatic

	column UnitàMisura
		dataType: string
		summarizeBy: none
		sourceColumn: UnitàMisura

		annotation SummarizationSetBy = Automatic

	column CodiceSoggetto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceSoggetto

		annotation SummarizationSetBy = Automatic

	column CodiceCategoria
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceCategoria

		annotation SummarizationSetBy = Automatic

	column DataDocumento
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataDocumento
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Mezzo
		dataType: string
		summarizeBy: none
		sourceColumn: Mezzo

		annotation SummarizationSetBy = Automatic

	column Indice
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Indice

		annotation SummarizationSetBy = Automatic

	partition FACT_Magazzino = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bb824426-3526-4734-9406-d0645879f240" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bb824426-3526-4734-9406-d0645879f240"]}[Data],
				    MAGAZZINO_ = #"bb824426-3526-4734-9406-d0645879f240"{[entity="MAGAZZINO",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(MAGAZZINO_,{{"Articolo", "CodiceArticolo"}, {"Quantità", "Quantity"}, {"Data", "Date"}, {"Deposito", "CodiceDeposito"}, {"Movimento", "TipoMovimento"}, {"Unità", "UnitàMisura"}, {"Soggetto", "CodiceSoggetto"}, {"Categoria", "CodiceCategoria"}, {"Data Documento", "DataDocumento"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione
