table FACT_Ordini

	column CodiceOrdine
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceOrdine

		annotation SummarizationSetBy = Automatic

	column CodiceClienteVendita
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceClienteVendita

		annotation SummarizationSetBy = Automatic

	column CodiceClienteFatturazione
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceClienteFatturazione

		annotation SummarizationSetBy = Automatic

	column CodiceSpedizione
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceSpedizione

		annotation SummarizationSetBy = Automatic

	column DataRegistrazione
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: DataRegistrazione
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DataSpedizione
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataSpedizione

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ARC
		dataType: string
		summarizeBy: none
		sourceColumn: ARC

		annotation SummarizationSetBy = Automatic

	column CodiceSpedizioniere
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceSpedizioniere

		annotation SummarizationSetBy = Automatic

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceArticolo

		annotation SummarizationSetBy = Automatic

	column CodiceDeposito
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceDeposito

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VAT
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: VAT

		annotation SummarizationSetBy = Automatic

	column NetWeight
		dataType: double
		summarizeBy: sum
		sourceColumn: NetWeight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CodiceCategoria
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceCategoria

		annotation SummarizationSetBy = Automatic

	column CodiceCausaleVendita
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceCausaleVendita

		annotation SummarizationSetBy = Automatic

	column Accisa
		dataType: double
		summarizeBy: sum
		sourceColumn: Accisa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DensitàTA
		dataType: double
		summarizeBy: sum
		sourceColumn: DensitàTA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Densità15C
		dataType: double
		summarizeBy: sum
		sourceColumn: Densità15C

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_Ordini = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"3f7bdf65-9391-4d91-9a41-2a5b893c841a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="3f7bdf65-9391-4d91-9a41-2a5b893c841a"]}[Data],
				    ORDINI_ = #"3f7bdf65-9391-4d91-9a41-2a5b893c841a"{[entity="ORDINI",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(ORDINI_,{{"Ordine", "CodiceOrdine"}, {"Codice Cliente Vendita", "CodiceClienteVendita"}, {"Codice Cliente Fatturazione", "CodiceClienteFatturazione"}, {"Codice Spedizione", "CodiceSpedizione"}, {"Data Registrazione", "DataRegistrazione"}, {"Data Spedizione", "DataSpedizione"}, {"Spedizioniere", "CodiceSpedizioniere"}, {"Articolo", "CodiceArticolo"}, {"Ubicazione", "CodiceDeposito"}, {"VAT _", "VAT"}, {"Net Weight", "NetWeight"}, {"Categoria", "CodiceCategoria"}, {"Cod_ Causale Vendita", "CodiceCausaleVendita"}, {"Densità T_A_", "DensitàTA"}, {"Densità 15 C", "Densità15C"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
