table FACT_Giacenza

	column Date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Data
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_Giacenza = m
		mode: import
		queryGroup: GOOGLE_SHEETS
		source =
				let
				    Origine = PowerBI.Dataflows(null),
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Origine{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"a989179f-746e-4a2d-9ae7-6fadb9c887fd" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="a989179f-746e-4a2d-9ae7-6fadb9c887fd"]}[Data],
				    tab_giacenza1 = #"a989179f-746e-4a2d-9ae7-6fadb9c887fd"{[entity="tab_giacenza"]}[Data],
				    #"Riordinate colonne" = Table.ReorderColumns(tab_giacenza1,{"Data", "Articolo", "Qta", "Importo"}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Riordinate colonne",{{"Qta", "Quantità"}}),
				    #"Filtrate righe" = Table.SelectRows(#"Rinominate colonne", each [Data] <> null and [Data] <> "")
				in
				    #"Filtrate righe"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table
