table FACT_MovimentiCG

	column EntryNo
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: EntryNo

		annotation SummarizationSetBy = Automatic

	column CodiceConto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceConto

		annotation SummarizationSetBy = Automatic

	column DataRegistrazione
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataRegistrazione

		annotation SummarizationSetBy = Automatic

	column TipoDocumento
		dataType: string
		summarizeBy: none
		sourceColumn: TipoDocumento

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Descrizione
		dataType: string
		summarizeBy: none
		sourceColumn: Descrizione

		annotation SummarizationSetBy = Automatic

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reparto
		dataType: string
		summarizeBy: none
		sourceColumn: Reparto

		annotation SummarizationSetBy = Automatic

	column Progetto
		dataType: string
		summarizeBy: none
		sourceColumn: Progetto

		annotation SummarizationSetBy = Automatic

	column CodiceSorgente
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceSorgente

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Categoria
		dataType: string
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column GruppoRegistrazioneProdotto
		dataType: string
		summarizeBy: none
		sourceColumn: GruppoRegistrazioneProdotto

		annotation SummarizationSetBy = Automatic

	column DataDocumento
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataDocumento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DocumentoEsterno
		dataType: string
		summarizeBy: none
		sourceColumn: DocumentoEsterno

		annotation SummarizationSetBy = Automatic

	column TipoSorgente
		dataType: string
		summarizeBy: none
		sourceColumn: TipoSorgente

		annotation SummarizationSetBy = Automatic

	column CodiceSoggetto
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceSoggetto

		annotation SummarizationSetBy = Automatic

	column MezzoTrasporto
		dataType: string
		summarizeBy: none
		sourceColumn: MezzoTrasporto

		annotation SummarizationSetBy = Automatic

	partition FACT_MovimentiCG = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"3244ac51-6341-4378-accd-b5b3e508daba" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="3244ac51-6341-4378-accd-b5b3e508daba"]}[Data],
				    MOVCG_ = #"3244ac51-6341-4378-accd-b5b3e508daba"{[entity="FACT_MovimentiCG",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(MOVCG_,{{"Entry No_", "EntryNo"}, {"Conto", "CodiceConto"}, {"Data Registrazione", "DataRegistrazione"}, {"Tipo Documento", "TipoDocumento"}, {"Source Code", "CodiceSorgente"}, {"Quantità", "Quantity"}, {"Gen_ Prod_ Posting Group", "GruppoRegistrazioneProdotto"}, {"Data Documento", "DataDocumento"}, {"Documento Esterno", "DocumentoEsterno"}, {"Source Type", "TipoSorgente"}, {"Source No_", "CodiceSoggetto"}, {"Mezzo Trasporto", "MezzoTrasporto"}}),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Rinominate colonne",{{"DataRegistrazione", type date}, {"DataDocumento", type date}, {"Quantity", type number}, {"Importo", type number}, {"EntryNo", Int64.Type}})
				in
				    #"Modificato tipo"

	annotation PBI_ResultType = Table
