table FACT_MagazzinoCMP

	column TipoMovimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ArticoloBase
		dataType: string
		summarizeBy: none
		sourceColumn: ArticoloBase

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Data
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Anno
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Anno

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_MagazzinoCMP = m
		mode: import
		queryGroup: QUERY_CMP
		source = ```
				// MAGAZZINO_CMP

				let
				    // 1. FILTRI TEMPORALI
				    Start = RangeStart,
				    End = RangeEnd,
				    Origine = FACT_Magazzino,

				    // 2. MOVIMENTI FISICI (WAREHOUSE)
				    FiltratoIPEM = Table.SelectRows(Origine, each [Date] >= Start and [Date] <= End and [CodiceDeposito] = "IPEM"),
				    // Escludiamo gli acquisti dal flusso fisico per evitare raddoppi: prenderemo quelli valorizzati sotto
				    FisicoSenzaAcquisti = Table.SelectRows(FiltratoIPEM, each [TipoMovimento] <> "Acquisto"),
				    FisicoClean = Table.SelectColumns(FisicoSenzaAcquisti, {"Date", "CodiceArticolo", "TipoMovimento", "Quantity"}),
				    FisicoTyped = Table.TransformColumnTypes(FisicoClean, {{"Quantity", type number}, {"Date", type date}, {"CodiceArticolo", type text}}),
				    FisicoTon = Table.TransformColumns(FisicoTyped, {{"Quantity", each _ / 1000}}), // Kg -> Ton
				    FisicoFinal = Table.AddColumn(FisicoTon, "Importo", each 0, type number),

				    // 3. APERTURA ANNUALE (OPENING)
				    OpeningTyped = Table.TransformColumnTypes(FACT_Giacenza, {{"Date", type date}, {"Quantity", type number}, {"Importo", type number}, {"CodiceArticolo", type text}}),
				    OpeningAdded = Table.AddColumn(OpeningTyped, "TipoMovimento", each "Opening", type text),
				    OpeningSchema = Table.SelectColumns(OpeningAdded, {"Date", "CodiceArticolo", "TipoMovimento", "Quantity", "Importo"}),

				    // 4. ACQUISTI VALORIZZATI
				    // Mix: Allineamento date e join
				    Mix_Normalized = Table.RenameColumns(FACT_QuantitaMix, {{"QuantityBIL", "Quantity"}}, MissingField.Ignore),
				    Mix_DateFix = Table.TransformColumnTypes(Mix_Normalized, {{"Date", type date}}),
				    Mix_Costi_DateFix = Table.TransformColumnTypes(FACT_MixCosti, {{"Data", type date}}),

				    Mix_Join = Table.NestedJoin(Mix_DateFix, {"CodiceArticolo", "Date"}, Mix_Costi_DateFix, {"Articolo", "Data"}, "C", JoinKind.LeftOuter),
				    Mix_Final = Table.ExpandTableColumn(Mix_Join, "C", {"Importo"}, {"Importo"}),
				    Mix_FixNull = Table.ReplaceValue(Mix_Final, null, 0, Replacer.ReplaceValue, {"Importo"}),
				    Mix_Clean = Table.SelectColumns(Mix_FixNull, {"Date", "CodiceArticolo", "TipoMovimento", "Quantity", "Importo"}),

				    // Propano: Allineamento date
				    Propano_DateFix = Table.TransformColumnTypes(FACT_QuantitaPropano, {{"Data", type date}}),
				    Propano_Clean = Table.SelectColumns(Propano_DateFix, {"Data", "Articolo", "Movimento", "Quantità", "Importo"}, MissingField.Ignore),
				    Propano_Normalized = Table.RenameColumns(Propano_Clean, {{"Data", "Date"}, {"Articolo", "CodiceArticolo"}, {"Movimento", "TipoMovimento"}, {"Quantità", "Quantity"}}),

				    // 5. UNIFICAZIONE FINALE
				    Unione = Table.Combine({FisicoFinal, OpeningSchema, Mix_Clean, Propano_Normalized}),


				    // Calcolo Attributi
				    AddArticoloBase = Table.AddColumn(Unione, "ArticoloBase", each
				        let art = Text.From([CodiceArticolo]) in
				        if art = "2" or art = "2T" then "2" else if art = "1" or art = "1T" then "1" else art, type text
				    ),
				    AddAnno = Table.AddColumn(AddArticoloBase, "Anno", each Date.Year([Date]), Int64.Type),

				    // Ordinamento interno al giorno: Opening(0) -> Acquisto(1) -> Rettifica(2) -> Vendita(3)
				    AddPriority = Table.AddColumn(AddAnno, "Priority", each
				        if [TipoMovimento] = "Opening" then 0
				        else if [TipoMovimento] = "Acquisto" then 1
				        else if Text.Contains([TipoMovimento], "Rettifica") then 2 else 3, Int64.Type
				    ),

				    Final = Table.SelectRows(AddPriority, each [ArticoloBase] <> null and [Date] <> null),
				    #"Modificato tipo" = Table.TransformColumnTypes(Final,{{"Quantity", type number}}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Modificato tipo",{{"Date", "Data"}, {"CodiceArticolo", "Articolo"}, {"TipoMovimento", "Movimento"}, {"Quantity", "Quantità"}})
				in
				    #"Rinominate colonne"
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table
