table FACT_Stock

	column Movimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QtaProgressiva
		dataType: double
		summarizeBy: sum
		sourceColumn: QtaProgressiva

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValoreProgressivo
		dataType: double
		summarizeBy: sum
		sourceColumn: ValoreProgressivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMP
		dataType: double
		summarizeBy: sum
		sourceColumn: CMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ArticoloBase
		dataType: string
		summarizeBy: none
		sourceColumn: ArticoloBase

		annotation SummarizationSetBy = Automatic

	column ValoreMov
		dataType: double
		summarizeBy: sum
		sourceColumn: ValoreMov

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Articolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Anno
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Anno

		annotation SummarizationSetBy = Automatic

	column Quantità
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Tab_Stock = m
		mode: import
		queryGroup: QUERY_CMP
		source = ```
				// TAB_STOCK
				
				let
				    Source = MAGAZZINO_CMP,
				    Sorted = Table.Sort(Source, {{"ArticoloBase", Order.Ascending}, {"Anno", Order.Ascending}, {"Data", Order.Ascending}, {"Priority", Order.Ascending}}),
				
				    CalcoloCMP = Table.Group(Sorted, {"ArticoloBase", "Anno"}, {
				        {"Dati", (tbl) => 
				            let
				                Records = Table.ToRecords(tbl),
				                Count = List.Count(Records),
				                
				                Iterazione = List.Generate(
				                    () => [
				                        i = 0,
				                        q = Records{0}[Quantità],
				                        v = Records{0}[Importo],
				                        // Se il primo movimento è un carico, calcoliamo il CMP iniziale
				                        cmp = if Records{0}[Quantità] > 0 then Records{0}[Importo] / Records{0}[Quantità] else 0,
				                        valMov = Records{0}[Importo]
				                    ],
				                    each [i] < Count,
				                    each let
				                        n = [i] + 1,
				                        row = Records{n},
				                        
				                        isAcquistoReale = (row[Movimento] = "Acquisto" and row[Importo] <> 0),
				                        isOpening = (row[Movimento] = "Opening"),
				                        
				                        qNew = if isOpening then row[Quantità] else [q] + row[Quantità],
				                        
				                        // Valore Movimento:
				                        // Se è un carico (Acquisto con prezzo o Opening), prendiamo l'importo
				                        // Se è uno scarico o una rettifica, usiamo il CMP calcolato precedentemente
				                        vMov = if isOpening or isAcquistoReale then row[Importo] 
				                               else row[Quantità] * [cmp],
				                        
				                        vNew = if isOpening then row[Importo] else [v] + vMov,
				                        
				                        // Il CMP si aggiorna SOLO su nuovi carichi valorizzati
				                        cmpNew = if (isAcquistoReale or isOpening) and qNew > 0 then vNew / qNew else [cmp]
				                    in
				                        [
				                            i = n,
				                            q = qNew,
				                            v = vNew,
				                            cmp = cmpNew,
				                            valMov = vMov
				                        ],
				                    each [[q], [v], [cmp], [valMov]]
				                ),
				                
				                // Unione dei risultati
				                Columns = Table.FromRecords(Iterazione),
				                Result = Table.FromColumns(
				                    Table.ToColumns(tbl) & Table.ToColumns(Columns),
				                    Table.ColumnNames(tbl) & {"QtaProgressiva", "ValoreProgressivo", "CMP", "ValoreMov"}
				                )
				            in
				                Result,
				            type table
				        }
				    }),
				
				    Expanded = Table.ExpandTableColumn(CalcoloCMP, "Dati", 
				        {"Data", "Articolo", "Movimento", "Quantità", "Importo", "QtaProgressiva", "ValoreProgressivo", "CMP", "ValoreMov"}
				    ),
				
				    Typed = Table.TransformColumnTypes(Expanded,{{"QtaProgressiva", type number}, {"ValoreProgressivo", type number}, {"CMP", type number}, {"ValoreMov", type number}, {"Data", type date}, {"Articolo", type text}, {"Movimento", type text}, {"Quantità", type number}, {"Importo", type number}})
				in
				    Typed
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

