table FACT_DocumentoVendita

	column CodiceClienteFatturazione
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceClienteFatturazione

		annotation SummarizationSetBy = Automatic

	column CodiceArticolo
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceArticolo

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrezzoUnitario
		dataType: double
		summarizeBy: sum
		sourceColumn: PrezzoUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostoTrasporto
		dataType: double
		summarizeBy: sum
		sourceColumn: CostoTrasporto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CodiceDeposito
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceDeposito

		annotation SummarizationSetBy = Automatic

	column TipoDocumento
		dataType: string
		summarizeBy: none
		sourceColumn: TipoDocumento

		annotation SummarizationSetBy = Automatic

	column DataSpedizione
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataSpedizione

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DataRegistrazione
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: DataRegistrazione

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TipoRiga
		dataType: string
		summarizeBy: none
		sourceColumn: TipoRiga

		annotation SummarizationSetBy = Automatic

	column CodiceCategoria
		dataType: string
		summarizeBy: none
		sourceColumn: CodiceCategoria

		annotation SummarizationSetBy = Automatic

	column Progetto
		dataType: string
		summarizeBy: none
		sourceColumn: Progetto

		annotation SummarizationSetBy = Automatic

	column Reparto
		dataType: string
		summarizeBy: none
		sourceColumn: Reparto

		annotation SummarizationSetBy = Automatic

	column MezzoTrasporto
		dataType: string
		summarizeBy: none
		sourceColumn: MezzoTrasporto

		annotation SummarizationSetBy = Automatic

	column GruppoRegistrazioneProdotto
		dataType: string
		summarizeBy: none
		sourceColumn: GruppoRegistrazioneProdotto

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: string
		summarizeBy: none
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	partition FACT_DocumentoVendita = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Origine = PowerPlatform.Dataflows(null),
				    Workspaces = Origine{[Id="Workspaces"]}[Data],
				    #"903f203e-7eed-4c27-ba7b-509c81c128c4" = Workspaces{[workspaceId="903f203e-7eed-4c27-ba7b-509c81c128c4"]}[Data],
				    #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a" = #"903f203e-7eed-4c27-ba7b-509c81c128c4"{[dataflowId="bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"]}[Data],
				    #"DOCUMENTO VENDITA_" = #"bf21c8a4-9eaf-4781-ac5e-5e3f7ff0ec5a"{[entity="DOCUMENTO VENDITA",version=""]}[Data],
				    #"Rinominate colonne" = Table.RenameColumns(#"DOCUMENTO VENDITA_",{{"Codice Cliente Fatturazione", "CodiceClienteFatturazione"}, {"No_", "CodiceArticolo"}, {"Prezzo Unitario", "PrezzoUnitario"}, {"Costo Trasporto", "CostoTrasporto"}, {"Ubicazione", "CodiceDeposito"}, {"Tipo Documento", "TipoDocumento"}, {"Data Spedizione", "DataSpedizione"}, {"Data Registrazione", "DataRegistrazione"}, {"Tipo Riga", "TipoRiga"}, {"Categoria", "CodiceCategoria"}, {"Mezzo Trasporto", "MezzoTrasporto"}, {"Gen_ Prod_ Posting Group", "GruppoRegistrazioneProdotto"}})
				in
				    #"Rinominate colonne"

	annotation PBI_ResultType = Table
