table MAGAZZINO_CMP

	column Movimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ArticoloBase
		dataType: string
		summarizeBy: none
		sourceColumn: ArticoloBase

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Data

		variation Variazione
			isDefault
			relationship: ae216beb-ada6-4aa9-ac37-7d39a9705475
			defaultHierarchy: LocalDateTable_cde1638f-9b5b-4103-b5d1-6bc3f5431ca2.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Articolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Anno
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Anno

		annotation SummarizationSetBy = Automatic

	column Quantità
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MAGAZZINO_CMP = m
		mode: import
		queryGroup: QUERY_CMP
		source = ```
				// MAGAZZINO_CMP
				
				let
				    // 1. FILTRI TEMPORALI
				    Start = RangeStart,
				    End = RangeEnd,
				    Origine = MAGAZZINO,
				    
				    // 2. MOVIMENTI FISICI (WAREHOUSE)
				    FiltratoIPEM = Table.SelectRows(Origine, each [Data] >= Start and [Data] <= End and [Deposito] = "IPEM"),
				    // Escludiamo gli acquisti dal flusso fisico per evitare raddoppi: prenderemo quelli valorizzati sotto
				    FisicoSenzaAcquisti = Table.SelectRows(FiltratoIPEM, each [Movimento] <> "Acquisto"),
				    FisicoClean = Table.SelectColumns(FisicoSenzaAcquisti, {"Data", "Articolo", "Movimento", "Quantità"}),
				    FisicoTyped = Table.TransformColumnTypes(FisicoClean, {{"Quantità", type number}, {"Data", type date}, {"Articolo", type text}}),
				    FisicoTon = Table.TransformColumns(FisicoTyped, {{"Quantità", each _ / 1000}}), // Kg -> Ton
				    FisicoFinal = Table.AddColumn(FisicoTon, "Importo", each 0, type number),
				
				    // 3. APERTURA ANNUALE (OPENING)
				    // Gestione sicura dei nomi: cerchiamo 'Valore Giacenza' e rinominiamo in 'Importo'
				    OpeningColFix = Table.RenameColumns(TAB_GIACENZA, {{"Valore Giacenza", "Importo"}}, MissingField.Ignore),
				    OpeningAdded = Table.AddColumn(OpeningColFix, "Movimento", each "Opening", type text),
				    OpeningSchema = Table.SelectColumns(OpeningAdded, {"Data", "Articolo", "Movimento", "Quantità", "Importo"}, MissingField.Ignore),
				    OpeningTyped = Table.TransformColumnTypes(OpeningSchema, {{"Data", type date}, {"Quantità", type number}, {"Importo", type number}, {"Articolo", type text}}),
				
				    // 4. ACQUISTI VALORIZZATI
				    // Mix: Allineamento date e join
				    Mix_Normalized = Table.RenameColumns(QUANTITA_MIX, {{"Qta_BIL", "Quantità"}}, MissingField.Ignore),
				    Mix_DateFix = Table.TransformColumnTypes(Mix_Normalized, {{"Data", type date}}),
				    Mix_Costi_DateFix = Table.TransformColumnTypes(MIX_COSTI, {{"Data", type date}}),
				    
				    Mix_Join = Table.NestedJoin(Mix_DateFix, {"Articolo", "Data"}, Mix_Costi_DateFix, {"Articolo", "Data"}, "C", JoinKind.LeftOuter),
				    Mix_Final = Table.ExpandTableColumn(Mix_Join, "C", {"Importo"}, {"Importo"}),
				    Mix_FixNull = Table.ReplaceValue(Mix_Final, null, 0, Replacer.ReplaceValue, {"Importo"}),
				    Mix_Clean = Table.SelectColumns(Mix_FixNull, {"Data", "Articolo", "Movimento", "Quantità", "Importo"}),
				   
				    // Propano: Allineamento date
				    Propano_DateFix = Table.TransformColumnTypes(QUANTITA_PROPANO, {{"Data", type date}}),
				    Propano_Clean = Table.SelectColumns(Propano_DateFix, {"Data", "Articolo", "Movimento", "Quantità", "Importo"}, MissingField.Ignore),
				
				    // 5. UNIFICAZIONE FINALE
				    Unione = Table.Combine({FisicoFinal, OpeningTyped, Mix_Clean, Propano_Clean}),
				    
				    
				    // Calcolo Attributi
				    AddArticoloBase = Table.AddColumn(Unione, "ArticoloBase", each 
				        let art = Text.From([Articolo]) in
				        if art = "2" or art = "2T" then "2" else if art = "1" or art = "1T" then "1" else art, type text
				    ),
				    AddAnno = Table.AddColumn(AddArticoloBase, "Anno", each Date.Year([Data]), Int64.Type),
				
				    // Ordinamento interno al giorno: Opening(0) -> Acquisto(1) -> Rettifica(2) -> Vendita(3)
				    AddPriority = Table.AddColumn(AddAnno, "Priority", each 
				        if [Movimento] = "Opening" then 0 
				        else if [Movimento] = "Acquisto" then 1 
				        else if Text.Contains([Movimento], "Rettifica") then 2 else 3, Int64.Type
				    ),
				    
				    Final = Table.SelectRows(AddPriority, each [ArticoloBase] <> null and [Data] <> null),
				    #"Modificato tipo" = Table.TransformColumnTypes(Final,{{"Quantità", type number}})
				in
				    #"Modificato tipo"
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

