table PROPANO_COSTI

	column Data
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Data
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Articolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Movimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Nave
		dataType: string
		summarizeBy: none
		sourceColumn: Nave

		annotation SummarizationSetBy = Automatic

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition PROPANO_COSTI = m
		mode: import
		queryGroup: QUERY_CMP
		source = ```
				// PROPANO_COSTI
				let
				    Source = MOVCG,
				
				    Filtrato =
				        Table.SelectRows(
				            Source,
				            each 
				                List.Contains(
				                    {
				                        "4020002","2030004","4030003",
				                        "4030002","4030004","4030006",
				                        "4030007","4030008",
				                        "3400023","3400025"
				                    },
				                    [Conto]
				                )
				        ),
				    #"Rinominate colonne" = Table.RenameColumns(Filtrato,{{"Mezzo Trasporto", "Nave"}}),
				
				    Raggruppo =
				        Table.Group(
				            #"Rinominate colonne",
				            {"Nave","Data Registrazione"},
				            {
				                {"Importo", each List.Sum([Importo]), type number}
				            }
				        ),
				    #"Modificato tipo" = Table.TransformColumnTypes(Raggruppo,{{"Data Registrazione", type date}}),
				    #"Rinominate colonne1" = Table.RenameColumns(#"Modificato tipo",{{"Data Registrazione", "Data"}}),
				    #"Aggiunta colonna personalizzata" = Table.AddColumn(#"Rinominate colonne1", "Articolo", each "2"),
				    #"Riordinate colonne" = Table.ReorderColumns(#"Aggiunta colonna personalizzata",{"Data", "Nave", "Articolo", "Importo"}),
				    #"Modificato tipo1" = Table.TransformColumnTypes(#"Riordinate colonne",{{"Articolo", type text}}),
				    #"Aggiunta colonna personalizzata1" = Table.AddColumn(#"Modificato tipo1", "Movimento", each "Acquisto"),
				    #"Riordinate colonne1" = Table.ReorderColumns(#"Aggiunta colonna personalizzata1",{"Data", "Articolo", "Movimento", "Nave", "Importo"}),
				    #"Modificato tipo2" = Table.TransformColumnTypes(#"Riordinate colonne1",{{"Movimento", type text}})
				in
				    #"Modificato tipo2"
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

