table QUANTITA_MIX

	column Data
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Data
		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Articolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Movimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Qta_BIL
		dataType: double
		summarizeBy: sum
		sourceColumn: Qta_BIL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Qta_RESA
		dataType: double
		summarizeBy: sum
		sourceColumn: Qta_RESA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition QUANTITA_MIX = m
		mode: import
		queryGroup: QUERY_CMP
		source = ```
				// QUANTITA_MIX
				
				let
				//--------------------------------------------------
				// FILTRI
				//--------------------------------------------------
				    filtro_articolo = {"1","1T"},
				    filtro_cliente = {"C00991","C01049"},
				
				//--------------------------------------------------
				// SORGENTI
				//--------------------------------------------------
				    Ordini = ORDINI,
				    Clienti = CLIENTI,
				    Articoli = ARTICOLI,
				    Calendario = CALENDARIO,
				
				//--------------------------------------------------
				// JOIN CLIENTI
				//--------------------------------------------------
				    Join1 = Table.NestedJoin(
				        Ordini,
				        {"Codice Cliente Fatturazione"},
				        Clienti,
				        {"Codice Cliente"},
				        "Clienti",
				        JoinKind.Inner
				    ),
				    ExpandClienti = Table.ExpandTableColumn(
				        Join1,
				        "Clienti",
				        {"Codice Cliente"}
				    ),
				
				//--------------------------------------------------
				// JOIN ARTICOLI
				//--------------------------------------------------
				    Join2 = Table.NestedJoin(
				        ExpandClienti,
				        {"Articolo"},
				        Articoli,
				        {"Codice Articolo"},
				        "Articoli",
				        JoinKind.Inner
				    ),
				    ExpandArticoli = Table.ExpandTableColumn(
				        Join2,
				        "Articoli",
				        {"Codice Articolo"}
				    ),
				
				//--------------------------------------------------
				// FILTRI (TREATAS equivalente)
				//--------------------------------------------------
				    FilteredRows = Table.SelectRows(
				        ExpandArticoli,
				        each List.Contains(filtro_cliente, [Codice Cliente]) and
				             List.Contains(filtro_articolo, [Codice Articolo])
				    ),
				
				//--------------------------------------------------
				// JOIN CALENDARIO
				//--------------------------------------------------
				    JoinCal = Table.NestedJoin(
				        FilteredRows,
				        {"Data Registrazione"},
				        Calendario,
				        {"Date"},
				        "Calendario",
				        JoinKind.Inner
				    ),
				    ExpandCal = Table.ExpandTableColumn(
				        JoinCal,
				        "Calendario",
				        {"Date"}
				    ),
				
				//==================================================
				// CALCOLI (EX MISURE DAX)
				//==================================================
				
				//--------------------------------------------------
				// QTA BIL (da Quantity)
				//--------------------------------------------------
				    AddQtaBIL = Table.AddColumn(
				        ExpandCal,
				        "Qta_BIL_calc",
				        each 
				            if Text.StartsWith([Ordine], "ODA") then
				                if [Quantity] = null then null
				                else if [Quantity] >= 1000 then [Quantity] / 1000
				                else [Quantity]
				            else null,
				        type number
				    ),
				
				//--------------------------------------------------
				// QTA RESA (da Net Weight) ✅ CORRETTA
				//--------------------------------------------------
				    AddQtaRESA = Table.AddColumn(
				        AddQtaBIL,
				        "Qta_RESA_calc",
				        each 
				            if Text.StartsWith([Ordine], "ODA") and 
				               List.Contains(filtro_articolo, [Codice Articolo]) then
				                let nw = [Net Weight]
				                in 
				                    if nw = null then null
				                    else if nw >= 1000 then nw / 1000
				                    else nw
				            else null,
				        type number
				    ),
				    #"Rimosse altre colonne" = Table.SelectColumns(AddQtaRESA,{"Codice Articolo", "Date", "Qta_BIL_calc", "Qta_RESA_calc"}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse altre colonne",{{"Qta_BIL_calc", "Qta_BIL"}, {"Qta_RESA_calc", "Qta_RESA"}}),
				    #"Riordinate colonne" = Table.ReorderColumns(#"Rinominate colonne",{"Date", "Codice Articolo", "Qta_BIL", "Qta_RESA"}),
				    #"Rinominate colonne1" = Table.RenameColumns(#"Riordinate colonne",{{"Date", "Data"}}),
				    #"Filtrate righe" = Table.SelectRows(#"Rinominate colonne1", each [Qta_BIL] <> null and [Qta_BIL] <> ""),
				    #"Aggiunta colonna personalizzata" = Table.AddColumn(#"Filtrate righe", "Movimento", each "Acquisto"),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Aggiunta colonna personalizzata",{{"Movimento", type text}}),
				    #"Riordinate colonne1" = Table.ReorderColumns(#"Modificato tipo",{"Data", "Codice Articolo", "Movimento", "Qta_BIL", "Qta_RESA"}),
				    #"Rinominate colonne2" = Table.RenameColumns(#"Riordinate colonne1",{{"Codice Articolo", "Articolo"}})
				
				in
				    #"Rinominate colonne2"
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

