table Tab_CMP_Progressivo

	column Data
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Articolo
		dataType: string
		summarizeBy: none
		sourceColumn: Articolo

		annotation SummarizationSetBy = Automatic

	column Movimento
		dataType: string
		summarizeBy: none
		sourceColumn: Movimento

		annotation SummarizationSetBy = Automatic

	column Quantità
		dataType: double
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Importo
		dataType: double
		summarizeBy: sum
		sourceColumn: Importo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Tab_CMP_Progressivo = m
		mode: import
		queryGroup: DIM
		source = ```
				let
				
				//--------------------------------------------------
				// SORGENTI
				//--------------------------------------------------
				
				DF = QUERY_BASE_DF,
				WB = QUERY_BASE_WEB,
				
				ORDINI_src = DF[ORDINI],
				DOCVEN_src = DF[DOCVEN],
				CAMBI_src = DF[CAMBI],
				
				PREZZI_src = WB[PREZZI],
				
				//--------------------------------------------------
				// PREZZI + CAMBI
				//--------------------------------------------------
				
				PREZZI_K =
				Table.AddColumn(
				    Table.AddColumn(PREZZI_src, "Anno", each Date.Year([Data]), Int64.Type),
				    "Mese", each Date.Month([Data]), Int64.Type
				),
				
				PREZZI_MIN =
				Table.Group(
				    PREZZI_K,
				    {"Anno","Mese","Fornitore"},
				    {{"Prezzo USD", each List.First(List.RemoveNulls([Prezzo USD])), type number}}
				),
				
				CAMBI_K =
				Table.AddColumn(
				    Table.AddColumn(CAMBI_src, "Anno", each Date.Year([Data]), Int64.Type),
				    "Mese", each Date.Month([Data]), Int64.Type
				),
				
				CAMBI_MIN =
				Table.Group(
				    CAMBI_K,
				    {"Anno","Mese"},
				    {{"Tasso", each List.First(List.RemoveNulls([Tasso])), type number}}
				),
				
				//--------------------------------------------------
				// ACQUISTI MIX
				//--------------------------------------------------
				
				ORDINI_F =
				Table.SelectRows(
				    ORDINI_src,
				    each Text.StartsWith([Ordine], "ODA")
				),
				
				ORDINI_K =
				Table.AddColumn(
				    Table.AddColumn(ORDINI_F, "Anno", each Date.Year([Data Registrazione]), Int64.Type),
				    "Mese", each Date.Month([Data Registrazione]), Int64.Type
				),
				
				// ✅ Qta safe
				ORDINI_Q =
				Table.AddColumn(
				    ORDINI_K,
				    "Qta",
				    each 
				        let q = [Quantity]
				        in if q = null then null
				           else if q >= 1000 then q / 1000
				           else q,
				    type number
				),
				
				// JOIN PREZZI
				ORDINI_JOIN_P =
				Table.NestedJoin(
				    ORDINI_Q,
				    {"Anno","Mese","Codice Cliente Fatturazione"},
				    PREZZI_MIN,
				    {"Anno","Mese","Fornitore"},
				    "P",
				    JoinKind.LeftOuter
				),
				
				ORDINI_P =
				Table.ExpandTableColumn(ORDINI_JOIN_P,"P",{"Prezzo USD"}),
				
				// JOIN CAMBI
				ORDINI_JOIN_C =
				Table.NestedJoin(
				    ORDINI_P,
				    {"Anno","Mese"},
				    CAMBI_MIN,
				    {"Anno","Mese"},
				    "C",
				    JoinKind.LeftOuter
				),
				
				ORDINI_PC =
				Table.ExpandTableColumn(ORDINI_JOIN_C,"C",{"Tasso"}),
				
				// ✅ IMPORTO SAFE (divisione protetta)
				ORDINI_VAL =
				Table.AddColumn(
				    ORDINI_PC,
				    "Importo",
				    each 
				        let 
				            q = [Qta],
				            p = [Prezzo USD],
				            t = [Tasso]
				        in 
				            if q = null or p = null or t = null or t = 0 
				            then null 
				            else q * (p / t),
				    type number
				),
				
				ACQ_MIX =
				Table.Group(
				    ORDINI_VAL,
				    {"Anno","Mese"},
				    {
				        {"Quantità", each List.Sum(List.RemoveNulls([Qta])), type number},
				        {"Importo", each List.Sum(List.RemoveNulls([Importo])), type number}
				    }
				),
				
				ACQ_MIX_OUT =
				Table.AddColumn(
				    Table.AddColumn(ACQ_MIX,"Articolo",each "1"),
				    "Movimento",each "Acquisto"
				),
				
				//--------------------------------------------------
				// VENDITE
				//--------------------------------------------------
				
				DOC_K =
				Table.AddColumn(
				    Table.AddColumn(DOCVEN_src,"Anno",each Date.Year([Data Registrazione]),Int64.Type),
				    "Mese",each Date.Month([Data Registrazione]),Int64.Type
				),
				
				VEN =
				Table.Group(
				    DOC_K,
				    {"Anno","Mese"},
				    {
				        {"Quantità", each List.Sum(List.RemoveNulls([Quantity])), type number}
				    }
				),
				
				VEN_OUT =
				Table.AddColumn(
				    Table.AddColumn(VEN,"Articolo",each "1"),
				    "Movimento",each "Vendita"
				),
				
				// ✅ Negativo safe
				VEN_FIX =
				Table.TransformColumns(
				    VEN_OUT,
				    {
				        {"Quantità", each if _ = null then null else -_, type number}
				    }
				),
				
				VEN_FIX2 =
				Table.AddColumn(
				    VEN_FIX,
				    "Importo",
				    each null,
				    type number
				),
				
				//--------------------------------------------------
				// COMBINE
				//--------------------------------------------------
				
				OUT =
				Table.Combine({
				    ACQ_MIX_OUT,
				    VEN_FIX2
				}),
				
				ADD_DATE =
				Table.AddColumn(
				    OUT,
				    "Data",
				    each #date([Anno],[Mese],1),
				    type date
				),
				
				FINAL =
				Table.SelectColumns(
				    ADD_DATE,
				    {"Data","Articolo","Movimento","Quantità","Importo"}
				),
				
				RESULT =
				Table.TransformColumnTypes(
				    FINAL,
				    {
				        {"Articolo", type text},
				        {"Movimento", type text}
				    }
				)
				
				in
				    RESULT
				```

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

